---
spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/SareLee/
          uri: https://github.com/SareLee/matchmaker.git
          username: sare73lee@gmail.com
          password: github$123
          default-label: main
          #searchPaths: matchmaker
          #clone-on-start: true
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8001

management.endpoints.web.exposure.include: health,info,bus-refresh  